export type Payment = {
  id: string;
  amount: number;
  status: "pending" | "processing" | "success" | "failed";
  email: string;
};

export const payments: Payment[] = [
  {
    id: "26f3",
    amount: 419,
    status: "pending",
    email: "user6@gmail.com",
  },
  {
    id: "04af",
    amount: 288,
    status: "pending",
    email: "user666@gmail.com",
  },
  {
    id: "0eee",
    amount: 493,
    status: "failed",
    email: "user529@yahoo.com",
  },
  {
    id: "2666",
    amount: 478,
    status: "failed",
    email: "user264@yahoo.com",
  },
  {
    id: "0748",
    amount: 105,
    status: "success",
    email: "user144@example.com",
  },
  {
    id: "1add",
    amount: 50,
    status: "processing",
    email: "user41@hotmail.com",
  },
  {
    id: "0523",
    amount: 432,
    status: "failed",
    email: "user529@gmail.com",
  },
  {
    id: "09bc",
    amount: 183,
    status: "processing",
    email: "user541@example.com",
  },
  {
    id: "2208",
    amount: 460,
    status: "pending",
    email: "user172@gmail.com",
  },
  {
    id: "23d3",
    amount: 454,
    status: "success",
    email: "user155@hotmail.com",
  },
  {
    id: "077f",
    amount: 446,
    status: "processing",
    email: "user239@hotmail.com",
  },
  {
    id: "212f",
    amount: 413,
    status: "failed",
    email: "user640@yahoo.com",
  },
  {
    id: "1abc",
    amount: 346,
    status: "pending",
    email: "user670@hotmail.com",
  },
  {
    id: "133d",
    amount: 115,
    status: "failed",
    email: "user886@hotmail.com",
  },
  {
    id: "14af",
    amount: 136,
    status: "success",
    email: "user962@hotmail.com",
  },
  {
    id: "0d85",
    amount: 362,
    status: "pending",
    email: "user871@yahoo.com",
  },
  {
    id: "1d8e",
    amount: 476,
    status: "success",
    email: "user994@gmail.com",
  },
  {
    id: "2205",
    amount: 379,
    status: "success",
    email: "user496@hotmail.com",
  },
  {
    id: "1ffa",
    amount: 316,
    status: "failed",
    email: "user766@hotmail.com",
  },
  {
    id: "1d31",
    amount: 97,
    status: "success",
    email: "user436@gmail.com",
  },
  {
    id: "155a",
    amount: 141,
    status: "success",
    email: "user401@example.com",
  },
  {
    id: "0d66",
    amount: 441,
    status: "failed",
    email: "user814@hotmail.com",
  },
  {
    id: "1667",
    amount: 345,
    status: "failed",
    email: "user600@gmail.com",
  },
  {
    id: "1845",
    amount: 464,
    status: "success",
    email: "user301@yahoo.com",
  },
  {
    id: "0bff",
    amount: 222,
    status: "processing",
    email: "user881@gmail.com",
  },
  {
    id: "1097",
    amount: 256,
    status: "processing",
    email: "user650@hotmail.com",
  },
  {
    id: "16b6",
    amount: 396,
    status: "failed",
    email: "user190@gmail.com",
  },
  {
    id: "1659",
    amount: 208,
    status: "success",
    email: "user225@hotmail.com",
  },
  {
    id: "1c99",
    amount: 72,
    status: "pending",
    email: "user528@hotmail.com",
  },
  {
    id: "1aa5",
    amount: 415,
    status: "processing",
    email: "user978@yahoo.com",
  },
  {
    id: "1358",
    amount: 413,
    status: "processing",
    email: "user768@example.com",
  },
  {
    id: "09fe",
    amount: 316,
    status: "processing",
    email: "user530@example.com",
  },
  {
    id: "2458",
    amount: 386,
    status: "processing",
    email: "user252@hotmail.com",
  },
  {
    id: "0d22",
    amount: 77,
    status: "success",
    email: "user37@yahoo.com",
  },
  {
    id: "1caf",
    amount: 481,
    status: "pending",
    email: "user124@hotmail.com",
  },
  {
    id: "0a02",
    amount: 371,
    status: "failed",
    email: "user886@gmail.com",
  },
  {
    id: "1a8e",
    amount: 470,
    status: "pending",
    email: "user244@gmail.com",
  },
  {
    id: "1c68",
    amount: 76,
    status: "failed",
    email: "user54@hotmail.com",
  },
  {
    id: "1536",
    amount: 300,
    status: "pending",
    email: "user991@yahoo.com",
  },
  {
    id: "188d",
    amount: 289,
    status: "processing",
    email: "user164@hotmail.com",
  },
  {
    id: "08c2",
    amount: 313,
    status: "failed",
    email: "user573@hotmail.com",
  },
  {
    id: "0ac1",
    amount: 209,
    status: "failed",
    email: "user701@yahoo.com",
  },
  {
    id: "23bb",
    amount: 458,
    status: "processing",
    email: "user310@hotmail.com",
  },
  {
    id: "151b",
    amount: 201,
    status: "failed",
    email: "user19@example.com",
  },
  {
    id: "0798",
    amount: 173,
    status: "failed",
    email: "user268@hotmail.com",
  },
  {
    id: "1ea3",
    amount: 390,
    status: "processing",
    email: "user213@hotmail.com",
  },
  {
    id: "16d5",
    amount: 498,
    status: "processing",
    email: "user964@yahoo.com",
  },
  {
    id: "0e7a",
    amount: 276,
    status: "processing",
    email: "user751@yahoo.com",
  },
  {
    id: "03f5",
    amount: 427,
    status: "failed",
    email: "user357@gmail.com",
  },
  {
    id: "1a2c",
    amount: 113,
    status: "processing",
    email: "user992@hotmail.com",
  },
  {
    id: "1332",
    amount: 358,
    status: "processing",
    email: "user495@example.com",
  },
  {
    id: "2560",
    amount: 452,
    status: "pending",
    email: "user974@gmail.com",
  },
  {
    id: "2627",
    amount: 351,
    status: "success",
    email: "user864@gmail.com",
  },
  {
    id: "0ef7",
    amount: 498,
    status: "success",
    email: "user74@gmail.com",
  },
  {
    id: "1028",
    amount: 145,
    status: "processing",
    email: "user790@gmail.com",
  },
  {
    id: "1f9e",
    amount: 450,
    status: "processing",
    email: "user256@example.com",
  },
  {
    id: "1545",
    amount: 270,
    status: "processing",
    email: "user141@example.com",
  },
  {
    id: "0607",
    amount: 344,
    status: "pending",
    email: "user128@example.com",
  },
  {
    id: "1427",
    amount: 394,
    status: "success",
    email: "user833@gmail.com",
  },
  {
    id: "20fe",
    amount: 271,
    status: "failed",
    email: "user986@example.com",
  },
  {
    id: "1b35",
    amount: 336,
    status: "pending",
    email: "user621@example.com",
  },
  {
    id: "14bc",
    amount: 182,
    status: "processing",
    email: "user448@hotmail.com",
  },
  {
    id: "1bf5",
    amount: 288,
    status: "success",
    email: "user812@hotmail.com",
  },
  {
    id: "203a",
    amount: 156,
    status: "failed",
    email: "user953@hotmail.com",
  },
  {
    id: "1a35",
    amount: 167,
    status: "success",
    email: "user326@example.com",
  },
  {
    id: "0906",
    amount: 493,
    status: "success",
    email: "user214@yahoo.com",
  },
  {
    id: "1494",
    amount: 457,
    status: "pending",
    email: "user750@example.com",
  },
  {
    id: "0a4a",
    amount: 374,
    status: "success",
    email: "user282@hotmail.com",
  },
  {
    id: "1753",
    amount: 277,
    status: "processing",
    email: "user632@example.com",
  },
  {
    id: "0747",
    amount: 285,
    status: "pending",
    email: "user409@hotmail.com",
  },
  {
    id: "1e8e",
    amount: 155,
    status: "processing",
    email: "user561@example.com",
  },
  {
    id: "1909",
    amount: 449,
    status: "pending",
    email: "user86@gmail.com",
  },
  {
    id: "1a46",
    amount: 133,
    status: "pending",
    email: "user920@gmail.com",
  },
  {
    id: "25eb",
    amount: 323,
    status: "processing",
    email: "user432@gmail.com",
  },
  {
    id: "15c6",
    amount: 219,
    status: "processing",
    email: "user119@yahoo.com",
  },
  {
    id: "0428",
    amount: 128,
    status: "failed",
    email: "user724@gmail.com",
  },
  {
    id: "26dd",
    amount: 115,
    status: "processing",
    email: "user959@yahoo.com",
  },
  {
    id: "0ed5",
    amount: 397,
    status: "processing",
    email: "user516@yahoo.com",
  },
  {
    id: "2109",
    amount: 264,
    status: "pending",
    email: "user126@yahoo.com",
  },
  {
    id: "265c",
    amount: 500,
    status: "failed",
    email: "user673@hotmail.com",
  },
  {
    id: "16c2",
    amount: 164,
    status: "processing",
    email: "user192@gmail.com",
  },
  {
    id: "0b19",
    amount: 458,
    status: "success",
    email: "user897@gmail.com",
  },
  {
    id: "1d4d",
    amount: 194,
    status: "success",
    email: "user75@gmail.com",
  },
  {
    id: "22f5",
    amount: 438,
    status: "processing",
    email: "user358@gmail.com",
  },
  {
    id: "22b1",
    amount: 456,
    status: "pending",
    email: "user632@yahoo.com",
  },
  {
    id: "0d79",
    amount: 212,
    status: "failed",
    email: "user338@gmail.com",
  },
  {
    id: "08f2",
    amount: 303,
    status: "processing",
    email: "user7@gmail.com",
  },
  {
    id: "07e6",
    amount: 418,
    status: "pending",
    email: "user640@yahoo.com",
  },
  {
    id: "248f",
    amount: 428,
    status: "processing",
    email: "user133@example.com",
  },
  {
    id: "1d01",
    amount: 498,
    status: "pending",
    email: "user244@hotmail.com",
  },
  {
    id: "0b0d",
    amount: 57,
    status: "failed",
    email: "user892@gmail.com",
  },
  {
    id: "0ca4",
    amount: 337,
    status: "pending",
    email: "user323@example.com",
  },
  {
    id: "10ee",
    amount: 214,
    status: "pending",
    email: "user261@hotmail.com",
  },
  {
    id: "26f8",
    amount: 420,
    status: "processing",
    email: "user931@hotmail.com",
  },
  {
    id: "1360",
    amount: 348,
    status: "pending",
    email: "user609@example.com",
  },
  {
    id: "05d4",
    amount: 263,
    status: "processing",
    email: "user651@gmail.com",
  },
  {
    id: "1011",
    amount: 365,
    status: "failed",
    email: "user298@gmail.com",
  },
  {
    id: "159f",
    amount: 429,
    status: "failed",
    email: "user104@gmail.com",
  },
  {
    id: "13c0",
    amount: 386,
    status: "success",
    email: "user510@example.com",
  },
  {
    id: "115f",
    amount: 460,
    status: "success",
    email: "user943@hotmail.com",
  },
  {
    id: "1918",
    amount: 475,
    status: "success",
    email: "user629@yahoo.com",
  },
  {
    id: "1397",
    amount: 112,
    status: "failed",
    email: "user403@yahoo.com",
  },
  {
    id: "1efb",
    amount: 403,
    status: "failed",
    email: "user728@example.com",
  },
  {
    id: "1722",
    amount: 85,
    status: "success",
    email: "user48@hotmail.com",
  },
  {
    id: "0a46",
    amount: 474,
    status: "pending",
    email: "user255@example.com",
  },
  {
    id: "0b92",
    amount: 405,
    status: "processing",
    email: "user969@hotmail.com",
  },
  {
    id: "244b",
    amount: 77,
    status: "success",
    email: "user299@yahoo.com",
  },
  {
    id: "0bcc",
    amount: 103,
    status: "processing",
    email: "user765@yahoo.com",
  },
  {
    id: "10a7",
    amount: 203,
    status: "success",
    email: "user254@yahoo.com",
  },
  {
    id: "25a1",
    amount: 180,
    status: "failed",
    email: "user662@hotmail.com",
  },
];
